### ISSUE TITLE
associations error undefined method

### ISSUE THREAD

**Issue by olegsobchuk** [amberframework/granite-orm#134]
Hi!

I'm trying `amber` with `granite-orm`. I created new app with relation `Company` -> `has_many users`, and `User` `belongs_to company`. I created records with pg console and tried to check result via `amber x`
```

company = Company.first
puts company.users
```
returns

```
undefined method 'users' for Nil (compile-time type is (Company | Nil))
puts c.users
```

for `belongs_to` the same

Thanks.

**EDIT**

versions:
amber 0.6.4
granite_orm 0.8.4

**Comment by drujensen** [comment]
Hi @olegsobchuk 

The call to `Company.first` will return a union type of (Company | Nil).  You will need to check to see  if its Nil before calling `users` since Nil doesn't have a method called `users.

```
if company = Company.first
  puts company.users
else
  puts "Not Found"
end
```

Crystal will see that company is not nil in the if block and will remove the Nil from the Union Type.

**Comment by faustinoaq** [comment]
Another alternative is using [.try](https://devdocs.io/crystal/api/0.24.1/object#try%28%26block%29-instance-method): `Company.first.try(&.users)`
