### ISSUE TITLE
Can't delete a record: undefined method 'destroy' for Nil?

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite-orm#145]
I'm using crystal 0.24.1 and granite-orm with sqlite3. The first part does indeed find the database record by id. I can print it but not delete it?. The rest of the error says 'compile-time type is (Database::Memo | Nil)?
```
  def delete_memo
    id = ask("Which memo: ").to_i
    memo = Memo.find id
    if memo
      printf("%s %s %s %s\n", memo.id, memo.entry_date, memo.title, memo.body)
    end
    memo.destroy
    puts "Utterly destroying this record!" unless memo
    ask_char("\n -- press any key to continue -- ")
  end
```
Maybe seniors shouldn't play with their kid's toys:)

**Comment by lebogan** [comment]
Update on my previous post. If I enclose the destroy method in an if clause, it compiles and actually works?
```
    memo = Memo.find id
    if memo
      memo.destroy
    end
```

**Comment by drujensen** [comment]
@lebogan Memo.find will return a union type of `(Memo | Nil)`.  The thing is, the next call was `memo.destroy` and since the return type could be Nil, it will fail to compile. 

Crystal has this cool feature that if you do an `if memo`, it will remove the Nil from the union in the if block, so the only thing left is a (Memo) type in the union.  Since the Memo class has a `destroy` method, then it compiles and everything is happy.

I hope that helps explain what's going on here.

**Comment by lebogan** [comment]
@drujensen  Thank you so much for that explanation.
