### ISSUE TITLE
Numeric casts and PostgreSQL

### ISSUE THREAD

**Issue by jhass** [amberframework/granite-orm#90]
crystal-pg returns an `Int32` or `Int64` depending on the actual value size (since PostgreSQL has arbitrary integer precision). Crystal doesn't support upcasting integers, so Granite has to use conversion to convert between different integer types. Normalizing everything to Int64 probably makes the most sense.

**Comment by drujensen** [comment]
@jhass I thought about only supporting Int64 but there are legacy db's out there that have Int32 fields.  I think its better to support casting in those cases.  It won't cast if it doesn't need too.

**Comment by jhass** [comment]
I have actual `can't cast Int32 to Int64' runtime errors because crystal-pg returns an `Int32` for an `INTEGER` column.

**Comment by robacarp** [comment]
Just ran into this because I'd written a migration with a column as an INT instead of a BIGINT.

I think the right solution here is to just do the right thing with any schema. Amber can be opinionated about making all new columns `BIGINT` but that isn't going to stop someone from wiring it up to a pre-existing database.

This is more likely because migrations use micrate, so a dev is manually choosing what types a column is manually anyway. A migration system with a dsl that makes choices for you has its drawbacks, but it would help the framework operate more consistently.

**Comment by drujensen** [comment]
You can specify custom primary keys now.
